### ISSUE TITLE
Needs Python package

### ISSUE THREAD

**Issue by nandoflorestan** [chris1610/barnum-proj#3]
This is neat, but you need to:

- put the python code inside a "barnum" directory / Python package
- create a setup.py
- register your package in the Python Package Index
- make a release (possibly using my https://pypi.python.org/pypi/releaser )

Why wouldn't you?

**Comment by chris1610** [comment]
It is up now. I'm sure there are things to do to clean it up but works now.

**Comment by nandoflorestan** [comment]
Terrific. Thanks!
