### ISSUE TITLE
Import error with python 3.4.3

### ISSUE THREAD

**Issue by stereomisha** [chris1610/barnum-proj#4]
I have an import error with my python version:

    root@9e6fbe11b7d0:/# python
    Python 3.4.3 (default, Jun 29 2015, 22:32:43) 
    [GCC 4.9.2] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from barnum import gen_data
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python3.4/site-packages/barnum/gen_data.py", line 22, in <module>
        import gencc
    ImportError: No module named 'gencc'

**Comment by bmcguirk** [comment]
+1.

**Comment by chris1610** [comment]
I've updated this and put version 0.3 out on pypi. It should work now.
