### ISSUE TITLE
Error: "Parent module '' not loaded, cannot perform relative import"

### ISSUE THREAD

**Issue by bmcguirk** [chris1610/barnum-proj#5]
So, was able to install via pypi today, which is great. I got two issues, this is the first one: 
Trying to load gen_data.py:

```
PS C:\Anaconda3\Lib\site-packages\barnum> python gen_data.py
Traceback (most recent call last):
  File "gen_data.py", line 22, in <module>
    from . import gencc
SystemError: Parent module '' not loaded, cannot perform relative import
```

**Comment by chris1610** [comment]
The packaging of barnum was not very pythonic so I made a change and uploaded it to pypi as version 0.5.

Try upgrading and see if it works better. You'll notice that I changed the API as well so you don't import gen_data.

Typical usage is now:
>>> import barnum
>>> barnum.create_cc_number()
('discover', ['6011969976015320'])
>>> barnum.create_name()
('Loren', 'Dehart')
>>>

**Comment by bmcguirk** [comment]
This and the other issue are now working great. Thanks - great library.
