### ISSUE TITLE
KeyError 'AS'

### ISSUE THREAD

**Issue by necarlson97** [chris1610/barnum-proj#9]
There is a line in your raw data for zip codes:
`"96799","-07.209975","-170.771600","PAGO PAGO","AS","AMERICAN SAMOA","PO BOX ONLY"`
The 'state' abbreviation `"AS"` causes a key error, if it happens to be chosen.
```
File "/usr/local/lib/python3.7/site-packages/barnum/gen_data.py", line 77, in create_phone
    area_code = random.choice(state_area_codes[all_zips[zip_code][1]])
KeyError: 'AS'
```

Seems like a quick fix just to remove this line from your raw data (sorry to the people of American Samoa `¯\_(ツ)_/¯` ).

Thanks

**Comment by remeika** [comment]
The people of American Samoa will rise up and add their area code to the Barnum dataset like a phoenix.
